### ISSUE TITLE
Implement homepage page component

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/catalog-politic#2]
The homepage needs to contain:
- generic information about the aim of the project
- a menu to navigate easily to the site contents
- a section dedicated to the API feature of the project

The design of the homepage should be taken from this UX design:

https://xd.adobe.com/spec/5328b672-cd71-431d-5a44-c4ddcb08eb40-2519/

**Comment by RaduCStefanescu** [comment]
In progress @ Dan Barbut

**Comment by Owlree** [comment]
The first two sections of the page were done in the basic scaffold of the website merged in https://github.com/code4romania/catalog-politic/commit/2084c66b12d69d3ca9d65a123bac41089656a55f.

**Comment by danut3101** [comment]
Ok I will take it
