### ISSUE TITLE
Implement navigation bar

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/catalog-politic#3]
The Homepage needs to contain a menu to access the features of the website.
The menu should contain the following entries:
- Prezidentiale - links to the list containing all the candidates for the presidential campaign
- Politicieni - link to the "Coming soon page"
- Partide - link to the "Coming soon page"
- Date - link to the details page for the API component of the project
- Vizualizari - link to the data vizualization and reports page
- Doneaza - link to the Code4Romania donation page

The menu design should be taken from this UX:
https://xd.adobe.com/spec/5328b672-cd71-431d-5a44-c4ddcb08eb40-2519/

**Comment by Owlree** [comment]
Merged in https://github.com/code4romania/catalog-politic/commit/2084c66b12d69d3ca9d65a123bac41089656a55f.
