### ISSUE TITLE
Implement candidates master page component

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/catalog-politic#4]
As a user of the Catalog Politic I want to have a page where I can see all the candidates for the presidential election.
The page should contain minimal information for each candidate as cards or list, the cards should be clickable and the design and look and feel should be similar to this UX design:

https://xd.adobe.com/spec/5328b672-cd71-431d-5a44-c4ddcb08eb40-2519/

**Comment by RaduCStefanescu** [comment]
In progress @ Ciprian Cozma

**Comment by Tzupy** [comment]
I'm  working on the candidate component :)
