### ISSUE TITLE
Implement candidate detail page component

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/catalog-politic#5]
As an user of Catalog Politic I want to be able to view the details of a candidate.

The details should follow the look and feel of the following design:

https://xd.adobe.com/spec/5328b672-cd71-431d-5a44-c4ddcb08eb40-2519/

**Comment by RaduCStefanescu** [comment]
In progress @calincrist

**Comment by calincrist** [comment]
I'm on it!
