### ISSUE TITLE
Create Directus data entry setup on AWS

### ISSUE THREAD

**Issue by Owlree** [code4romania/catalog-politic#9]
We decided to go with [Directus](https://directus.io/) for data entry. 

There are three issues (one bug and two feature requests, respectively) that are impacting us and we are tracking them on their repository—https://github.com/directus/api/issues/1167, https://github.com/directus/app/issues/8, and https://github.com/directus/api/issues/763. Only one of the latter needs to be implemented for Directus to fully meet our use case. However, none of the latter is necessary, and we can work around them, they are mainly UI nice-to-haves.

Instead of relying on Directus Cloud, we are going to deploy Directus using Docker on AWS ECS with AWS Fargate, and Aurora DB as the underlying database. We _must_ have an infrastructure as code setup for this, and we decided to go with vanilla CloudFormation (third parties were considered, but decided against since we are investing in the AWS ecosystem, and the infrastructure is basic).

Consequently, we need to have the following—

1. CloudFormation stack for underlying VPC and subnets, and other networking entities
2. CloudFormation stack for AuroraDB, on top of stack 1, deployed with seed Directus schema for our project
3. CloudFormation stack for a private cluster of Directus containers, deployed using Fargate, behind a public facing ELB, on top of stack 1
4. Minimal requirements policies that each stack requires for deployment. 

All services _must_ have proper CloudWatch configuration.

**Comment by RaduCStefanescu** [comment]
In progress @Owlree
